import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import * as iconv from 'iconv-lite'
import { afterEach, describe, expect, it } from 'vitest'
import { parseCliArgs } from './parse'
import { normalizeCliPayloadFilePath, resolveCliPayload } from './payload'

const tempFiles: string[] = []

describe('resolveCliPayload', () => {
  afterEach(() => {
    while (tempFiles.length > 0) {
      const filePath = tempFiles.pop()
      if (filePath && fs.existsSync(filePath)) {
        fs.rmSync(filePath, { force: true })
      }
    }
  })

  it('accepts utf-8 bom payload files generated by PowerShell', () => {
    const filePath = path.join(os.tmpdir(), `dude-cli-payload-${Date.now()}.json`)
    tempFiles.push(filePath)

    fs.writeFileSync(filePath, '\ufeff{"username":"admin","password":""}', 'utf8')

    expect(
      resolveCliPayload({
        payloadFile: filePath,
        flags: {}
      })
    ).toEqual({
      username: 'admin',
      password: ''
    })
  })

  it('recovers gb18030 payload files in auto mode before JSON fields are used', () => {
    const filePath = path.join(os.tmpdir(), `dude-cli-payload-gbk-${Date.now()}.json`)
    tempFiles.push(filePath)

    const payload = {
      ledgerId: 5,
      description: '收到基本户利息',
      entries: [
        {
          summary: '支付对账单手续费',
          subjectCode: '1002',
          debit: 3.8,
          credit: 0
        }
      ]
    }
    fs.writeFileSync(filePath, iconv.encode(JSON.stringify(payload), 'gb18030'))

    expect(
      resolveCliPayload({
        payloadFile: filePath,
        flags: {}
      })
    ).toEqual(payload)
  })

  it('honors explicit gbk payload encoding', () => {
    const filePath = path.join(os.tmpdir(), `dude-cli-payload-explicit-gbk-${Date.now()}.json`)
    tempFiles.push(filePath)

    const payload = {
      ledgerId: 5,
      description: '收到基本户利息'
    }
    fs.writeFileSync(filePath, iconv.encode(JSON.stringify(payload), 'gb18030'))

    expect(
      resolveCliPayload({
        payloadFile: filePath,
        payloadEncoding: 'gbk',
        flags: {}
      } as Parameters<typeof resolveCliPayload>[0] & { payloadEncoding: 'gbk' })
    ).toEqual(payload)
  })

  it('keeps numeric-looking CLI flag values as strings by default', () => {
    expect(
      resolveCliPayload({
        flags: {
          ledgerId: '12',
          keyword: '1002',
          enabled: 'true',
          disabled: 'false'
        }
      })
    ).toEqual({
      ledgerId: '12',
      keyword: '1002',
      enabled: true,
      disabled: false
    })
  })

  it('uses payload-file before stdin and payload-json, then applies explicit flag overrides', () => {
    const filePath = path.join(os.tmpdir(), `dude-cli-payload-priority-${Date.now()}.json`)
    tempFiles.push(filePath)

    fs.writeFileSync(
      filePath,
      JSON.stringify({
        ledgerId: 1,
        reportType: 'balance_sheet',
        period: '2026-01'
      }),
      'utf8'
    )

    expect(
      resolveCliPayload({
        payloadFile: filePath,
        payloadStdinJson: JSON.stringify({
          ledgerId: 2,
          reportType: 'income_statement'
        }),
        payloadJson: JSON.stringify({
          ledgerId: 3
        }),
        flags: {
          period: '2026-02'
        }
      })
    ).toEqual({
      ledgerId: 1,
      reportType: 'balance_sheet',
      period: '2026-02'
    })
  })

  it('reads stdin payload before payload-json and keeps explicit flags as the final override', () => {
    expect(
      resolveCliPayload({
        payloadStdinJson: JSON.stringify({
          ledgerId: 8,
          status: 'all'
        }),
        payloadJson: JSON.stringify({
          ledgerId: 9,
          status: 0
        }),
        flags: {
          status: '3'
        }
      })
    ).toEqual({
      ledgerId: 8,
      status: '3'
    })
  })

  it('rejects flag overrides when the payload root is not an object', () => {
    expect(() =>
      resolveCliPayload({
        payloadStdinJson: '[1,2,3]',
        flags: {
          ledgerId: '1'
        }
      })
    ).toThrow('payload 文件、stdin 或 JSON 的根节点不是对象')
  })

  it('converts WSL mount payload paths before Windows reads the file', () => {
    expect(normalizeCliPayloadFilePath('/mnt/d/tmp/voucher.json')).toBe(
      process.platform === 'win32' ? 'D:\\tmp\\voucher.json' : '/mnt/d/tmp/voucher.json'
    )
  })

  it('converts WSL native payload paths through the exported distro name on Windows', () => {
    const originalDistroName = process.env.DUDEACC_WSL_DISTRO_NAME
    process.env.DUDEACC_WSL_DISTRO_NAME = 'Ubuntu'

    try {
      expect(normalizeCliPayloadFilePath('/tmp/voucher.json')).toBe(
        process.platform === 'win32'
          ? '\\\\wsl.localhost\\Ubuntu\\tmp\\voucher.json'
          : '/tmp/voucher.json'
      )
    } finally {
      if (originalDistroName === undefined) {
        delete process.env.DUDEACC_WSL_DISTRO_NAME
      } else {
        process.env.DUDEACC_WSL_DISTRO_NAME = originalDistroName
      }
    }
  })

  it('only normalizes booleans inside nested flag-shaped payload values', () => {
    expect(
      resolveCliPayload({
        flags: {
          entries: [
            {
              subjectCode: '1002',
              debitAmount: '3000',
              isCashFlow: 'false'
            }
          ] as unknown as string
        }
      })
    ).toEqual({
      entries: [
        {
          subjectCode: '1002',
          debitAmount: '3000',
          isCashFlow: false
        }
      ]
    })
  })
})

describe('parseCliArgs payload encoding', () => {
  it('parses --encoding for payload decoding without treating it as a business flag', () => {
    const parsed = parseCliArgs([
      'voucher',
      'save',
      '--payload-file',
      'D:\\tmp\\payload.json',
      '--encoding',
      'gbk',
      '--ledgerId',
      '5'
    ])

    expect(parsed.payloadEncoding).toBe('gbk')
    expect(parsed.flags).toEqual({
      ledgerId: '5'
    })
  })
})
