import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { afterEach, describe, expect, it } from 'vitest'
import { normalizeCliPayloadFilePath, resolveCliPayload } from './payload'

const tempFiles: string[] = []

describe('resolveCliPayload', () => {
  afterEach(() => {
    while (tempFiles.length > 0) {
      const filePath = tempFiles.pop()
      if (filePath && fs.existsSync(filePath)) {
        fs.rmSync(filePath, { force: true })
      }
    }
  })

  it('accepts utf-8 bom payload files generated by PowerShell', () => {
    const filePath = path.join(os.tmpdir(), `dude-cli-payload-${Date.now()}.json`)
    tempFiles.push(filePath)

    fs.writeFileSync(filePath, '\ufeff{"username":"admin","password":""}', 'utf8')

    expect(
      resolveCliPayload({
        payloadFile: filePath,
        flags: {}
      })
    ).toEqual({
      username: 'admin',
      password: ''
    })
  })

  it('keeps numeric-looking CLI flag values as strings by default', () => {
    expect(
      resolveCliPayload({
        flags: {
          ledgerId: '12',
          keyword: '1002',
          enabled: 'true',
          disabled: 'false'
        }
      })
    ).toEqual({
      ledgerId: '12',
      keyword: '1002',
      enabled: true,
      disabled: false
    })
  })

  it('converts WSL mount payload paths before Windows reads the file', () => {
    expect(normalizeCliPayloadFilePath('/mnt/d/tmp/voucher.json')).toBe(
      process.platform === 'win32' ? 'D:\\tmp\\voucher.json' : '/mnt/d/tmp/voucher.json'
    )
  })

  it('converts WSL native payload paths through the exported distro name on Windows', () => {
    const originalDistroName = process.env.DUDEACC_WSL_DISTRO_NAME
    process.env.DUDEACC_WSL_DISTRO_NAME = 'Ubuntu'

    try {
      expect(normalizeCliPayloadFilePath('/tmp/voucher.json')).toBe(
        process.platform === 'win32'
          ? '\\\\wsl.localhost\\Ubuntu\\tmp\\voucher.json'
          : '/tmp/voucher.json'
      )
    } finally {
      if (originalDistroName === undefined) {
        delete process.env.DUDEACC_WSL_DISTRO_NAME
      } else {
        process.env.DUDEACC_WSL_DISTRO_NAME = originalDistroName
      }
    }
  })

  it('only normalizes booleans inside nested flag-shaped payload values', () => {
    expect(
      resolveCliPayload({
        flags: {
          entries: [
            {
              subjectCode: '1002',
              debitAmount: '3000',
              isCashFlow: 'false'
            }
          ] as unknown as string
        }
      })
    ).toEqual({
      entries: [
        {
          subjectCode: '1002',
          debitAmount: '3000',
          isCashFlow: false
        }
      ]
    })
  })
})
