import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { afterEach, describe, expect, it } from 'vitest'
import { resolveCliPayload } from './payload'

const tempFiles: string[] = []

describe('resolveCliPayload', () => {
  afterEach(() => {
    while (tempFiles.length > 0) {
      const filePath = tempFiles.pop()
      if (filePath && fs.existsSync(filePath)) {
        fs.rmSync(filePath, { force: true })
      }
    }
  })

  it('accepts utf-8 bom payload files generated by PowerShell', () => {
    const filePath = path.join(os.tmpdir(), `dude-cli-payload-${Date.now()}.json`)
    tempFiles.push(filePath)

    fs.writeFileSync(filePath, '\ufeff{"username":"admin","password":""}', 'utf8')

    expect(
      resolveCliPayload({
        payloadFile: filePath,
        flags: {}
      })
    ).toEqual({
      username: 'admin',
      password: ''
    })
  })

  it('keeps numeric-looking CLI flag values as strings by default', () => {
    expect(
      resolveCliPayload({
        flags: {
          ledgerId: '12',
          keyword: '1002',
          enabled: 'true',
          disabled: 'false'
        }
      })
    ).toEqual({
      ledgerId: '12',
      keyword: '1002',
      enabled: true,
      disabled: false
    })
  })

  it('only normalizes booleans inside nested flag-shaped payload values', () => {
    expect(
      resolveCliPayload({
        flags: {
          entries: [
            {
              subjectCode: '1002',
              debitAmount: '3000',
              isCashFlow: 'false'
            }
          ] as unknown as string
        }
      })
    ).toEqual({
      entries: [
        {
          subjectCode: '1002',
          debitAmount: '3000',
          isCashFlow: false
        }
      ]
    })
  })
})
