import type { DudeAPI } from './desktopApi'

export type IpcChannel = {
  [D in keyof DudeAPI]: `${D}:${keyof DudeAPI[D] & string}`
}[keyof DudeAPI]

export type IpcMethod<C extends IpcChannel> =
  C extends `${infer D extends keyof DudeAPI}:${infer M}`
    ? M extends keyof DudeAPI[D]
      ? DudeAPI[D][M]
      : never
    : never
export type IpcArgs<C extends IpcChannel> =
  IpcMethod<C> extends (...args: infer A) => unknown ? A : never
export type IpcResult<C extends IpcChannel> =
  IpcMethod<C> extends (...args: never[]) => infer R ? Awaited<R> : never

/** 显式运行时清单与共享 API 双向检查；增加或删除接口必须同步注册。 */
export const IPC_CHANNELS = {
  'auth:login': true,
  'auth:logout': true,
  'auth:getUsers': true,
  'auth:createUser': true,
  'auth:updateUser': true,
  'auth:deleteUser': true,
  'ledger:getAll': true,
  'ledger:create': true,
  'ledger:update': true,
  'ledger:delete': true,
  'ledger:getDeletionRisk': true,
  'ledger:getPeriods': true,
  'ledger:getStandardTemplates': true,
  'ledger:applyStandardTemplate': true,
  'subject:getAll': true,
  'subject:search': true,
  'subject:create': true,
  'subject:update': true,
  'subject:delete': true,
  'auxiliary:getAll': true,
  'auxiliary:getByCategory': true,
  'auxiliary:create': true,
  'auxiliary:update': true,
  'auxiliary:delete': true,
  'cashflow:getItems': true,
  'cashflow:getMappings': true,
  'cashflow:createMapping': true,
  'cashflow:updateMapping': true,
  'cashflow:deleteMapping': true,
  'plCarryForward:listRules': true,
  'plCarryForward:saveRules': true,
  'plCarryForward:preview': true,
  'plCarryForward:execute': true,
  'voucher:getNextNumber': true,
  'voucher:list': true,
  'voucher:getEntries': true,
  'voucher:batchAction': true,
  'voucher:swapPositions': true,
  'voucher:renumber': true,
  'voucher:save': true,
  'voucher:update': true,
  'initialBalance:list': true,
  'initialBalance:save': true,
  'period:getStatus': true,
  'period:close': true,
  'period:reopen': true,
  'settings:getSystemParams': true,
  'settings:getRuntimeDefaults': true,
  'settings:getUserPreferences': true,
  'settings:getWallpaperState': true,
  'settings:getLoginWallpaperState': true,
  'settings:getErrorLogStatus': true,
  'settings:chooseDiagnosticsLogDirectory': true,
  'settings:restoreDefaultDiagnosticsLogDirectory': true,
  'settings:setSystemParam': true,
  'settings:setUserPreferences': true,
  'settings:openErrorLogDirectory': true,
  'settings:exportDiagnosticsLogs': true,
  'settings:chooseWallpaper': true,
  'settings:applyWallpaperCrop': true,
  'settings:restoreDefaultWallpaper': true,
  'settings:getSubjectTemplate': true,
  'settings:getSubjectTemplateReference': true,
  'settings:listIndependentCustomSubjectTemplates': true,
  'settings:getIndependentCustomSubjectTemplate': true,
  'settings:parseSubjectTemplateImport': true,
  'settings:saveSubjectTemplate': true,
  'settings:saveIndependentCustomSubjectTemplate': true,
  'settings:downloadSubjectTemplate': true,
  'settings:importSubjectTemplate': true,
  'settings:clearSubjectTemplate': true,
  'settings:clearIndependentCustomSubjectTemplateEntries': true,
  'settings:deleteIndependentCustomSubjectTemplate': true,
  'auditLog:list': true,
  'auditLog:export': true,
  'backup:create': true,
  'backup:list': true,
  'backup:validate': true,
  'backup:import': true,
  'backup:delete': true,
  'backup:restore': true,
  'archive:export': true,
  'archive:list': true,
  'archive:validate': true,
  'archive:delete': true,
  'archive:getManifest': true,
  'eVoucher:import': true,
  'eVoucher:list': true,
  'eVoucher:verify': true,
  'eVoucher:parse': true,
  'eVoucher:convert': true,
  'reporting:generate': true,
  'reporting:list': true,
  'reporting:getDetail': true,
  'reporting:export': true,
  'reporting:exportBatch': true,
  'reporting:chooseTaxTemplateOutputDirectory': true,
  'reporting:exportTaxTemplate': true,
  'reporting:delete': true,
  'print:prepare': true,
  'print:getJobStatus': true,
  'print:getPreviewModel': true,
  'print:openPreview': true,
  'print:updatePreviewSettings': true,
  'print:print': true,
  'print:exportPdf': true,
  'print:dispose': true,
  'bookQuery:listSubjectBalances': true,
  'bookQuery:getDetailLedger': true,
  'bookQuery:getJournal': true,
  'bookQuery:getAuxiliaryBalances': true,
  'bookQuery:getAuxiliaryDetail': true,
  'bookQuery:export': true
} as const satisfies Record<IpcChannel, true>
